/************************************************************************************


                                  smb Utility

  File: string_j.h
  Description:
  History:

| partially translated by Yy

 ************************************************************************************/
#ifndef STRING_J_H
#define STRING_J_H

#define STRING_NULL    ""
#define STRING_UNKNOWN "Unknown"

//
//
#define STRING_FILEOPENDIALOG_CHRLOAD "Load CHR file(For importing)"
#define STRING_WINDOW_EMULATOR        "Emulator"
#define STRING_WINDOW_OBJLIST         "Level Objects List"
#define STRING_WINDOW_OBJVIEW         "Main Editing Window"

//
#define STRING_OBJVIEW_TITLE          "%s <%dpage>"
#define STRING_OBJVIEW_TITLE2         "%s <%d-%dpage>"

//
#define STRING_STATUSBAR_EMULOAD  "Loaded state"
#define STRING_STATUSBAR_EMUSAVE  "Saved state"
#define STRING_STATUSBAR_FILESAVE "Saved file"

//
#define STRING_FILEERROR_SAVE       "Failed to save"
#define STRING_FILEERROR_SAVEAS     "Failed to save as"
#define STRING_FILEERROR_FILEFORMAT "Found file format(file type) error"
#define STRING_FILEERROR_NOTFOUND   "Not found file"

//
#define STRING_CONFIRM_EXIT         "Save and exit? (Yes saves the rom and exits, no doesn't save and justs exits, and cancle goes back to the program)"
#define STRING_CONFIRM_RELOAD       "Changed file by other editor.\nReload?"
#define STRING_CONFIRM_DEMORECORD   "Start recording demonstration."
#define STRING_CONFIRM_DEMORECORD2  "Stoped recording demonstration."
#define STRING_CONFIRM_UPDATEWORLD  "Reflesh world data?"

//
#define STRING_OPTIONDIALOG_TITLE       "option"
#define STRING_OPTIONDIALOG_EMULATOR    "emulator"
#define STRING_OPTIONDIALOG_EDITOR      "editor"
#define STRING_OPTIONDIALOG_APPLICATION "application"

//
#define STRING_TOOLTIP_OPEN              "Open"
#define STRING_TOOLTIP_SAVE              "Save"
#define STRING_TOOLTIP_ROOM              "Choose room"
#define STRING_TOOLTIP_BADGUYS           "Edit Badguys"
#define STRING_TOOLTIP_MAP               "Edit Map"
#define STRING_TOOLTIP_TESTPLAY          "Test Level"
#define STRING_TOOLTIP_PAGETESTPLAY      "Test Page"
#define STRING_TOOLTIP_HALFPOINTTESTPLAY "Test Halfway Point"
#define STRING_TOOLTIP_STOP              "Stop Emulation"
#define STRING_TOOLTIP_TESTPLAYSETTING   "Testing Settings"

//
#define STRING_SENDOBJECT_SRCERROR "Can't send source object."
#define STRING_SENDOBJECT_DSTERROR "There are no objects in destination page."

#define STRING_UNDO_MENUTEXT              "&Undo %s"
#define STRING_UNDONAME_KEYEDIT           "Keyboard input"
#define STRING_UNDONAME_DLGEDIT           "Dialog input"
#define STRING_UNDONAME_SENDOBJ           "Send object"
#define STRING_UNDONAME_HEADDLG           "Setting(Option)"
#define STRING_UNDONAME_CHRLOAD           "Load charactor ROM"
#define STRING_UNDONAME_TOOLSTR           "Strings editor"
#define STRING_UNDONAME_TOOLLOOPBIN       "Loop editor"
#define STRING_UNDONAME_TOOLWORLD         "Auto reflesh world data"
#define STRING_UNDONAME_TOOLAREAROOM      "Edit first ROOM of AREA"
#define STRING_UNDONAME_TOOLDEMORECORDER  "Demo recording"
#define STRING_UNDONAME_TOOLOTHER         "Other setting"
#define STRING_UNDONAME_TOOLGLOBAL        "Setting"


#define STRING_POLEGFX_DEFAULT "default"
#define STRING_POLEGFX_ROPE    "rope"
#define STRING_POLEGFX_TREE    "tree"
#define STRING_POLEGFX_OTHER   "other"

#define STRING_SETTING_WORLDX   "world%d"
#define STRING_SETTING_WARPZONE "warpzone"
#define STRING_SETTING_1UP      "1UP mushroom"
#define STRING_SETTING_KOOPA    "Bowser"
#define STRING_SETTING_WORLD    "world"
#define STRING_SETTING_OTHER    "other"
#define STRING_SETTING_TITLE    "Other setting"


#define STRING_STRINGDATA_01 "Mario(Status bar)"
#define STRING_STRINGDATA_02 "Mario(Unknows, but I thought I remember where this text was used!)"
#define STRING_STRINGDATA_03 "mario(Ditto)"
#define STRING_STRINGDATA_04 "Luigi(Status bar)"
#define STRING_STRINGDATA_05 "World  time(Status Bar, the World and Time texts are the same line of text!)"
#define STRING_STRINGDATA_06 "World(On the World 1-1 ect screen)"
#define STRING_STRINGDATA_07 "Time up"
#define STRING_STRINGDATA_08 "Game over"
#define STRING_STRINGDATA_09 "Welcome to warp zone!"
#define STRING_STRINGDATA_10 "Thank you Mario!"
#define STRING_STRINGDATA_11 "Thank you Luigi!"
#define STRING_STRINGDATA_12 "but our princess is in"
#define STRING_STRINGDATA_13 "another castle!"
#define STRING_STRINGDATA_14 "your quest is over."
#define STRING_STRINGDATA_15 "we present you a new quest."
#define STRING_STRINGDATA_16 "push button b"
#define STRING_STRINGDATA_17 "to select a world"
#define STRING_STRINGDATA_18 "ｩ1985 Nintendo"
#define STRING_STRINGDATA_19 "1 player game"
#define STRING_STRINGDATA_20 "2 player game"

#define STRING_TESTPLAYSETTING_MARIO      "Small Mario"
#define STRING_TESTPLAYSETTING_SUPERMARIO "Big Mario"
#define STRING_TESTPLAYSETTING_FIREMARIO  "Fire Mario"

#define STRING_KEYCONFIG_EMU_A              "A"
#define STRING_KEYCONFIG_EMU_B              "B"
#define STRING_KEYCONFIG_EMU_SELECT         "Select"
#define STRING_KEYCONFIG_EMU_START          "Start"
#define STRING_KEYCONFIG_EMU_UP             "Up"
#define STRING_KEYCONFIG_EMU_DOWN           "Down"
#define STRING_KEYCONFIG_EMU_LEFT           "Left"
#define STRING_KEYCONFIG_EMU_RIGHT          "Right"
#define STRING_KEYCONFIG_EDIT_ADD1          "Object value +1"
#define STRING_KEYCONFIG_EDIT_DEC1          "Object value -1"
#define STRING_KEYCONFIG_EDIT_ADD16         "Object value +16"
#define STRING_KEYCONFIG_EDIT_DEC16         "Object value -16"
#define STRING_KEYCONFIG_EDIT_UP            "Object position to up"
#define STRING_KEYCONFIG_EDIT_DOWN          "Object position to down"
#define STRING_KEYCONFIG_EDIT_LEFT          "Object position to left"
#define STRING_KEYCONFIG_EDIT_RIGHT         "Object position to righht"
#define STRING_KEYCONFIG_EDIT_NEXTPAGE      "Next page"
#define STRING_KEYCONFIG_EDIT_PREVPAGE      "Previous page"
#define STRING_KEYCONFIG_EDIT_NEXTOBJ       "Next object"
#define STRING_KEYCONFIG_EDIT_PREVOBJ       "Previous object"
#define STRING_KEYCONFIG_EDIT_SAVEFILE      "File: Overwrite Save"
#define STRING_KEYCONFIG_EDIT_UNDO          "Edit: Undo"
#define STRING_KEYCONFIG_EDIT_ROOM          "Edit: Open room"
#define STRING_KEYCONFIG_EDIT_BADGUYS       "Edit: Badguys"
#define STRING_KEYCONFIG_EDIT_MAP           "Edit: Map(Level)"
#define STRING_KEYCONFIG_EDIT_TESTPLAY      "Emulator: Test play"
#define STRING_KEYCONFIG_EDIT_PAGETESTPLAY  "Emulator: Page test play"
#define STRING_KEYCONFIG_EDIT_PAGETESTPLAY2 "Emulator: Middle point test play"
#define STRING_KEYCONFIG_EDIT_STOP          "Emulator: Stop"
#define STRING_KEYCONFIG_EDIT_SAVEEMU       "Emulator: Save"
#define STRING_KEYCONFIG_EDIT_LOADEMU       "Emulator: Load"
#define STRING_KEYCONFIG_EDIT_EMUSETTING    "Emulator: Test play option"
#define STRING_KEYCONFIG_EDIT_NEXTWIN       "Window: Next"
#define STRING_KEYCONFIG_EDIT_PREVWIN       "Window: Previous"
#define STRING_KEYCONFIG_KEYACCEL           "Keyboard accelerator"
#define STRING_KEYCONFIG_EMULATOR           "Emulator"
#define STRING_KEYCONFIG_OVERLAPPED         "It is overlapped at %s - \"%s\"."
#define STRING_KEYCONFIG_INITIALIZE         "Load preset-key?"
#define STRING_KEYCONFIG_NOTIFY             "It is enabled at next start. "

#define STRING_KEYCONFIG_PRESET_DESKTOP     "Desktop PC (Ten key)"
#define STRING_KEYCONFIG_PRESET_NOTE        "Note PC"

#define STRING_OBJLIST_LENNAME   "Length:%d, %s"
#define STRING_OBJLIST_UNKNOWN   "Unknown object"
#define STRING_OBJLIST_CRASH     "*Freezes"
#define STRING_OBJLIST_BACK      "Background:%s"
#define STRING_OBJLIST_VIEWBLOCK "Scene:%s Block:%s"
#define STRING_OBJLIST_ROPE      "Lift's vertical rope"
#define STRING_OBJLIST_LENCASTLE "Castle, Length:%d"
#define STRING_OBJLIST_STEP      "Stairs, Length:%d, Height:%d"
#define STRING_OBJLIST_STEP98    "Stairs, Length:9 Height:8"
#define STRING_OBJLIST_STEP98_2  "*Stairs, Length:9, Height:8"
#define STRING_OBJLIST_NONE      "*Nothing"

#define STRING_OBJLIST_ROOM        "Room change[%.2xH(%s),w=%d,p=%d]"
#define STRING_OBJLIST_PAGECOMMAND "Page change : %.2d"
#define STRING_OBJLIST_HARD        " (Only after 5-3)"

#define STRING_SEA         "Sea"
#define STRING_SKY         "Ground"
#define STRING_UNDERGROUND "Under ground"
#define STRING_CASTLE      "Castle"

#define STRING_OBJLIST_COLUMN_BIN  "Hex"
#define STRING_OBJLIST_COLUMN_PAGE "Page"
#define STRING_OBJLIST_COLUMN_POS  "Position"
#define STRING_OBJLIST_COLUMN_TYPE "Type"

#define STRING_OBJDATA_MAP_B_01 "? Block (Mushroom)"
#define STRING_OBJDATA_MAP_B_02 "? Block (Coin)"
#define STRING_OBJDATA_MAP_B_03 "Hidden block (Coin)"
#define STRING_OBJDATA_MAP_B_04 "Hidden block (1UP mushroom)"
#define STRING_OBJDATA_MAP_B_05 "Brick (Mushroom)"
#define STRING_OBJDATA_MAP_B_06 "Brick (tree of beans)"
#define STRING_OBJDATA_MAP_B_07 "Brick (Star)"
#define STRING_OBJDATA_MAP_B_08 "Brick (10coins)"
#define STRING_OBJDATA_MAP_B_09 "Brick (1UP mushroom)"
#define STRING_OBJDATA_MAP_B_10 "Sideways pipe"
#define STRING_OBJDATA_MAP_B_11 "Used block"
#define STRING_OBJDATA_MAP_B_12 "Jump stand"
#define STRING_OBJDATA_MAP_B_13 "reverse L pipe"
#define STRING_OBJDATA_MAP_B_14 "pole"
#define STRING_OBJDATA_MAP_B_15 "*Nothing"
#define STRING_OBJDATA_MAP_B_16 "*Nothing"
#define STRING_OBJDATA_MAP_B_17 "island(cannon)"
#define STRING_OBJDATA_MAP_B_18 "Horizontal brick(seaplant)"
#define STRING_OBJDATA_MAP_B_19 "Horizontal block"
#define STRING_OBJDATA_MAP_B_20 "Horizontal coins"
#define STRING_OBJDATA_MAP_B_21 "Vertical brick(seaplant)"
#define STRING_OBJDATA_MAP_B_22 "Vertical block"
#define STRING_OBJDATA_MAP_B_23 "pipe(Player can't enter.)"
#define STRING_OBJDATA_MAP_B_24 "pipe(Player can enter.)"

#define STRING_OBJDATA_HELP_B12 ""//"ｷｬﾗｸﾀの１つ。ｷｬﾗｸﾀｵｰﾊﾞｰで表示されなくなると、ﾏﾘｵが挟まって出れなくなるので注意。"
#define STRING_OBJDATA_HELP_B13 ""//"高さ9固定。横からでも上からでも入れる。(横位置＋2)から2ｷｬﾗ分は、先に指定された障害物を消す。"
#define STRING_OBJDATA_HELP_B14 ""//"やたらと使用しないこと。1ﾙｰﾑに2回以上使用すると暴走しやすくなるので注意。"
#define STRING_OBJDATA_HELP_B23 ""//"長さを1にしても必ず2になる。"

#define STRING_OBJDATA_MAP_C_01 "Hole"
#define STRING_OBJDATA_MAP_C_02 "Balance's horizontal rope"
#define STRING_OBJDATA_MAP_C_03 "Bridge(V=7)"
#define STRING_OBJDATA_MAP_C_04 "Bridge(V=8)"
#define STRING_OBJDATA_MAP_C_05 "Bridge(V=10)"
#define STRING_OBJDATA_MAP_C_06 "Hole filled with water"
#define STRING_OBJDATA_MAP_C_07 "Horizontal ?Block(coin, V=3)"
#define STRING_OBJDATA_MAP_C_08 "Horizontal ?Block(coin, V=7)"

#define STRING_OBJDATA_HELP_C01 ""//"縦位置8から12の先指定したすべてのﾏｯﾌﾟｷｬﾗを消す。"
#define STRING_OBJDATA_HELP_C02 ""//"縦位置0固定"
#define STRING_OBJDATA_HELP_C06 ""//"縦位置10から12の先指定したすべてのﾏｯﾌﾟｷｬﾗを消す。"

#define STRING_OBJDATA_MAP_D_01 "Page skip"
#define STRING_OBJDATA_MAP_D_02 "Reverse L pipe"
#define STRING_OBJDATA_MAP_D_03 "Pole"
#define STRING_OBJDATA_MAP_D_04 "Axe"
#define STRING_OBJDATA_MAP_D_05 "Rope"
#define STRING_OBJDATA_MAP_D_06 "Bridge"
#define STRING_OBJDATA_MAP_D_07 "Scroll stop (warp zone)"
#define STRING_OBJDATA_MAP_D_08 "Scroll stop"
#define STRING_OBJDATA_MAP_D_10 "Cheep-cheep(red, fly)"
#define STRING_OBJDATA_MAP_D_11 "Bullet Bill(Cheep-cheep)continuation"
#define STRING_OBJDATA_MAP_D_12 "stop continuation"
#define STRING_OBJDATA_MAP_D_13 "Loop command"
#define STRING_OBJDATA_MAP_D_14 "?"
#define STRING_OBJDATA_MAP_D_15 "*Freeze"

#define STRING_OBJDATA_HELP_D01 "Skip page"
#define STRING_OBJDATA_HELP_D03 ""//"やたらと使用しない事。1ﾙｰﾑに2回以上使用すると暴走しやすくなるので注意。"
#define STRING_OBJDATA_HELP_D04 ""//"縦位置6固定"
#define STRING_OBJDATA_HELP_D05 ""//"縦位置7固定"
#define STRING_OBJDATA_HELP_D06 ""//"縦位置8、長さ13固定"
#define STRING_OBJDATA_HELP_D12 ""//"連続出現ｷｬﾗを出した後、暴走を防ぐためにﾎﾟｰﾙを出す前に指定。"
#define STRING_OBJDATA_HELP_D13 ""//"ﾍﾟｰｼﾞ送りｺﾏﾝﾄﾞとｾｯﾄでﾙｰﾌﾟを形成する。"

#define STRING_OBJDATA_MAP_E_01 "Basic brick & scenery"
#define STRING_OBJDATA_MAP_E_02 "Change background"

#define STRING_OBJDATA_MAP_F_01 "Rope of lift"
#define STRING_OBJDATA_MAP_F_02 "vertical rope of balance lift"
#define STRING_OBJDATA_MAP_F_03 "Castle"
#define STRING_OBJDATA_MAP_F_04 "width:n, height:n, steps"
#define STRING_OBJDATA_MAP_F_05 "width:9, height:8, steps"
#define STRING_OBJDATA_MAP_F_06 "long reverse L pipe"
#define STRING_OBJDATA_MAP_F_07 "vertical balls"
#define STRING_OBJDATA_MAP_F_08 "Nothing"

#define STRING_OBJDATA_HELP_F01 ""//"縦位置0、長さ13固定。指定横位置において、先指定したすべてのﾏｯﾌﾟｷｬﾗを消す。"
#define STRING_OBJDATA_HELP_F02 ""//"縦位置1固定。指定横位置において、先指定したすべてのﾏｯﾌﾟｷｬﾗを消す。"
#define STRING_OBJDATA_HELP_F03 ""//"やたらと使用しないこと。多く使用すると暴走しやすくなる。"
#define STRING_OBJDATA_HELP_F05 ""//"長さ0～3 問題なし。\n長さ4～6 ｸﾞﾗﾌｨｯｸｽが潰れる。長さ7 ｸﾞﾗﾌｨｯｸｽが潰れる。(横位置+16)の位置に縦位置7の壊せないﾌﾞﾛｯｸ1個。"
#define STRING_OBJDATA_HELP_F07 ""//"ﾂﾀのようにつかまって上下移動が可能。縦位置2固定"

#define STRING_OBJDATA_BB_01 "Brick: None"
#define STRING_OBJDATA_BB_02 "Brick: Surface"
#define STRING_OBJDATA_BB_03 "Brick: Surface&ceiling"
#define STRING_OBJDATA_BB_04 "Brick: Surface&ceiling(3)"
#define STRING_OBJDATA_BB_05 "Brick: Surface&ceiling(4)"
#define STRING_OBJDATA_BB_06 "Brick: Surface&ceiling(8)"
#define STRING_OBJDATA_BB_07 "Brick: Surface(4)&ceiling"
#define STRING_OBJDATA_BB_08 "Brick: Surface(4)&ceiling(3)"
#define STRING_OBJDATA_BB_09 "Brick: Surface(4)&ceiling(4)"
#define STRING_OBJDATA_BB_10 "Brick: Surface(5)&ceiling"
#define STRING_OBJDATA_BB_11 "Brick: Surface"
#define STRING_OBJDATA_BB_12 "Brick: Surface(5)&ceiling(4)"
#define STRING_OBJDATA_BB_13 "Brick: Surface(8)&ceiling"
#define STRING_OBJDATA_BB_14 "Brick: Surface&ceiling&middle(5)"
#define STRING_OBJDATA_BB_15 "Brick: Surface&ceiling&middle(4)"
#define STRING_OBJDATA_BB_16 "Brick: All"

#define STRING_OBJDATA_T_01 "Not set"
#define STRING_OBJDATA_T_02 "400"
#define STRING_OBJDATA_T_03 "300"
#define STRING_OBJDATA_T_04 "200"

#define STRING_OBJDATA_P_01 "V=-1, H=1.5"
#define STRING_OBJDATA_P_02 "start of area: X, from another room; V=-1, H=1.5"
#define STRING_OBJDATA_P_03 "V=10, H=1.5"
#define STRING_OBJDATA_P_04 "V=4, H=1.5"
#define STRING_OBJDATA_P_07 "V=10, H=1.5(walking)"

#define STRING_OBJDATA_BC_01 "Nothing"
#define STRING_OBJDATA_BC_02 "In water"
#define STRING_OBJDATA_BC_03 "Wall"
#define STRING_OBJDATA_BC_04 "Over water"
#define STRING_OBJDATA_BC_05 "Night"
#define STRING_OBJDATA_BC_06 "Snow"
#define STRING_OBJDATA_BC_07 "Night and snow"
#define STRING_OBJDATA_BC_08 "Night and snow"

#define STRING_OBJDATA_MT_01 "Green and tree"
#define STRING_OBJDATA_MT_02 "Orange and mushroom"
#define STRING_OBJDATA_MT_03 "Guns"
#define STRING_OBJDATA_MT_04 "Clouds"

#define STRING_OBJDATA_V_01 "Nothing"
#define STRING_OBJDATA_V_02 "Clouds"
#define STRING_OBJDATA_V_03 "Mountain"
#define STRING_OBJDATA_V_04 "Fence"


#define STRING_OBJDATA_BADGUYS_01 "Koopa Troopa (green)"
#define STRING_OBJDATA_BADGUYS_02 "Koopa Troopa (red)"
#define STRING_OBJDATA_BADGUYS_03 "Buzzy Beetle"
#define STRING_OBJDATA_BADGUYS_04 "Koopa Troopa (red, both ways)"
#define STRING_OBJDATA_BADGUYS_05 "Koopa Troopa (green, stopped)"
#define STRING_OBJDATA_BADGUYS_06 "The Hammer Brothers"
#define STRING_OBJDATA_BADGUYS_07 "Little Goomba"
#define STRING_OBJDATA_BADGUYS_08 "Bloober"
#define STRING_OBJDATA_BADGUYS_09 "Bullet Bill"
#define STRING_OBJDATA_BADGUYS_10 "Koopa Paratroopa (green, stopped)"
#define STRING_OBJDATA_BADGUYS_11 "Cheep-cheep (green)"
#define STRING_OBJDATA_BADGUYS_12 "Cheep-cheep (red)"
#define STRING_OBJDATA_BADGUYS_13 "Podoboo"
#define STRING_OBJDATA_BADGUYS_14 "Pirana plants"
#define STRING_OBJDATA_BADGUYS_15 "Koopa Paratroopa (green, leaping)"
#define STRING_OBJDATA_BADGUYS_16 "Koopa Paratroopa (red, up&down)"
#define STRING_OBJDATA_BADGUYS_17 "Koopa Paratroopa (green, right&left)"
#define STRING_OBJDATA_BADGUYS_18 "Lakitu"
#define STRING_OBJDATA_BADGUYS_19 "Spiny"
#define STRING_OBJDATA_BADGUYS_20 "*Unknown"
#define STRING_OBJDATA_BADGUYS_21 "Cheep-cheep(fly)"
#define STRING_OBJDATA_BADGUYS_22 "Bowser's fire"
#define STRING_OBJDATA_BADGUYS_23 "*Crash"
#define STRING_OBJDATA_BADGUYS_24 "Bullet Bill(Cheep-cheep)continuation"
#define STRING_OBJDATA_BADGUYS_25 "*None"
#define STRING_OBJDATA_BADGUYS_28 "Fire Bar (right)"
#define STRING_OBJDATA_BADGUYS_29 "Fire Bar (right, fast)"
#define STRING_OBJDATA_BADGUYS_30 "Fire Bar (left)"
#define STRING_OBJDATA_BADGUYS_31 "Fire Bar (left, fast)"
#define STRING_OBJDATA_BADGUYS_32 "Long Fire Bar (right)"
#define STRING_OBJDATA_BADGUYS_33 "Fire Bar"
#define STRING_OBJDATA_BADGUYS_37 "lift(balance)"
#define STRING_OBJDATA_BADGUYS_38 "lift(up&down)"
#define STRING_OBJDATA_BADGUYS_39 "lift(up)"
#define STRING_OBJDATA_BADGUYS_40 "lift(down)"
#define STRING_OBJDATA_BADGUYS_41 "lift(right&left)"
#define STRING_OBJDATA_BADGUYS_42 "lift(fall)"
#define STRING_OBJDATA_BADGUYS_43 "lift(surfing)"
#define STRING_OBJDATA_BADGUYS_44 "short lift(up)"
#define STRING_OBJDATA_BADGUYS_45 "short lift(down)"
#define STRING_OBJDATA_BADGUYS_46 "Bowser, King of the Koopa"
#define STRING_OBJDATA_BADGUYS_47 "*Unknown"
#define STRING_OBJDATA_BADGUYS_48 "*Unknown"
#define STRING_OBJDATA_BADGUYS_51 "Jumping board(fake)"
#define STRING_OBJDATA_BADGUYS_53 "Warp Zone"
#define STRING_OBJDATA_BADGUYS_54 "Mushroom retainers"
#define STRING_OBJDATA_BADGUYS_56 "2 Little Goomba(V=10)"
#define STRING_OBJDATA_BADGUYS_57 "3 Little Goomba(V=10)"
#define STRING_OBJDATA_BADGUYS_58 "2 Little Goomba(V=6)"
#define STRING_OBJDATA_BADGUYS_59 "3 Little Goomba(V=6)"
#define STRING_OBJDATA_BADGUYS_60 "2 Koopa Troopa (green, V=10)"
#define STRING_OBJDATA_BADGUYS_61 "3 Koopa Troopa (green, V=10)"
#define STRING_OBJDATA_BADGUYS_62 "2 Koopa Troopa (green, V=6)"
#define STRING_OBJDATA_BADGUYS_63 "3 Koopa Troopa (green, V=6)"

#endif
