//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by resources.rc
//
#define IDS_PROGRAMNAME                 179
#define IDS_VERSION_CONTRIBUTION        180
#define IDS_EMPTY                       181
#define IDS_UNKNOWN                     182
#define IDS_LOGVIEW_FILESAVE            183
#define IDS_LOGVIEW_FILEOPEN            184
#define IDS_LOGVIEW_LOADCHR             185
#define IDS_FILEOPENDIALOG_CHRLOAD      186
#define IDS_WINDOW_EMULATOR             187
#define IDS_WINDOW_OBJLIST              188
#define IDS_WINDOW_OBJVIEW              189
#define IDS_OBJVIEW_TITLE               190
#define IDS_OBJVIEW_TITLE2              191
#define IDS_OBJVIEW_TOOLTIP             192
#define IDS_STATUSBAR_EMULOAD           193
#define IDS_STATUSBAR_EMUSAVE           194
#define IDS_STATUSBAR_FILESAVE          195
#define IDS_FILEERROR_SAVE              196
#define IDS_FILEERROR_SAVEAS            197
#define IDS_FILEERROR_FILEFORMAT        198
#define IDS_FILEERROR_NOTFOUND          199
#define IDS_CONFIRM_SAVE                200
#define IDS_CONFIRM_EXIT                201
#define IDS_CONFIRM_RELOAD              202
#define IDS_CONFIRM_DEMORECORD          203
#define IDS_CONFIRM_DEMORECORD2         204
#define IDS_CONFIRM_UPDATEWORLD         205
#define IDS_OPTIONDIALOG_TITLE          206
#define IDS_OPTIONDIALOG_EMULATOR       207
#define IDS_OPTIONDIALOG_EDITOR         208
#define IDS_OPTIONDIALOG_APPLICATION    209
#define IDS_OPTIONDIALOG_OBJECTVIEW     210
#define IDS_TOOLTIP_OPEN                211
#define IDS_TOOLTIP_SAVE                212
#define IDS_TOOLTIP_ROOM                213
#define IDS_TOOLTIP_BADGUYS             214
#define IDS_TOOLTIP_MAP                 215
#define IDS_TOOLTIP_TESTPLAY            216
#define IDS_TOOLTIP_PAGETESTPLAY        217
#define IDS_TOOLTIP_HALFPOINTTESTPLAY   218
#define IDS_TOOLTIP_STOP                219
#define IDS_TOOLTIP_TESTPLAYSETTING     220
#define IDS_SENDOBJECT_SRCERROR         221
#define IDS_SENDOBJECT_DSTERROR         222
#define IDS_SENDOBJECT_OVEROBJ          223
#define IDS_UNDO_MENUTEXT               224
#define IDS_UNDONAME_KEYEDIT            225
#define IDS_UNDONAME_DLGEDIT            226
#define IDS_UNDONAME_SENDOBJ            227
#define IDS_UNDONAME_HEADDLG            228
#define IDS_UNDONAME_CHRLOAD            229
#define IDS_UNDONAME_TOOLSTR            230
#define IDS_UNDONAME_TOOLLOOPBIN        231
#define IDS_UNDONAME_TOOLWORLD          232
#define IDS_UNDONAME_TOOLAREAROOM       233
#define IDS_UNDONAME_TOOLDEMORECORDER   234
#define IDS_UNDONAME_TOOLOTHER          235
#define IDS_POLEGFX_DEFAULT             237
#define IDS_POLEGFX_ROPE                238
#define IDS_POLEGFX_TREE                239
#define IDS_POLEGFX_OTHER               240
#define IDS_SETTING_WORLDX              241
#define IDS_SETTING_WARPZONE            242
#define IDS_SETTING_1UP                 243
#define IDS_SETTING_KOOPA               244
#define IDS_SETTING_WORLD               245
#define IDS_SETTING_OTHER               246
#define IDS_SETTING_TITLE               247
#define IDS_STRINGDATA_01               248
#define IDS_STRINGDATA_02               249
#define IDS_STRINGDATA_03               250
#define IDS_STRINGDATA_04               251
#define IDS_STRINGDATA_05               252
#define IDS_STRINGDATA_06               253
#define IDS_STRINGDATA_07               254
#define IDS_STRINGDATA_08               255
#define IDS_STRINGDATA_09               256
#define IDS_STRINGDATA_10               257
#define IDS_STRINGDATA_11               258
#define IDS_STRINGDATA_12               259
#define IDS_STRINGDATA_13               260
#define IDS_STRINGDATA_14               261
#define IDS_STRINGDATA_15               262
#define IDS_STRINGDATA_16               263
#define IDS_STRINGDATA_17               264
#define IDS_STRINGDATA_18               265
#define IDS_STRINGDATA_19               266
#define IDS_STRINGDATA_20               267
#define IDS_TESTPLAYSETTING_MARIO       268
#define IDS_TESTPLAYSETTING_SUPERMARIO  269
#define IDS_TESTPLAYSETTING_FIREMARIO   270
#define IDS_TESTPLAYSETTING_NONE        271
#define IDS_TESTPLAYSETTING_POS         272
#define IDS_TESTPLAYSETTING_DOT         273
#define IDS_EMULATOROPTION_JOYSTICK     274
#define IDS_KEYCONFIG_EMU_A             275
#define IDS_KEYCONFIG_EMU_B             276
#define IDS_KEYCONFIG_EMU_SELECT        277
#define IDS_KEYCONFIG_EMU_START         278
#define IDS_KEYCONFIG_EMU_UP            279
#define IDS_KEYCONFIG_EMU_DOWN          280
#define IDS_KEYCONFIG_EMU_LEFT          281
#define IDS_KEYCONFIG_EMU_RIGHT         282
#define IDS_KEYCONFIG_EDIT_ADD1         283
#define IDS_KEYCONFIG_EDIT_DEC1         284
#define IDS_KEYCONFIG_EDIT_ADD16        285
#define IDS_KEYCONFIG_EDIT_DEC16        286
#define IDS_KEYCONFIG_EDIT_UP           287
#define IDS_KEYCONFIG_EDIT_DOWN         288
#define IDS_KEYCONFIG_EDIT_LEFT         289
#define IDS_KEYCONFIG_EDIT_RIGHT        290
#define IDS_KEYCONFIG_EDIT_NEXTPAGE     291
#define IDS_KEYCONFIG_EDIT_PREVPAGE     292
#define IDS_KEYCONFIG_EDIT_NEXTOBJ      293
#define IDS_KEYCONFIG_EDIT_PREVOBJ      294
#define IDS_KEYCONFIG_EDIT_SAVEFILE     295
#define IDS_KEYCONFIG_EDIT_UNDO         296
#define IDS_KEYCONFIG_EDIT_ROOM         297
#define IDS_KEYCONFIG_EDIT_BADGUYS      298
#define IDS_KEYCONFIG_EDIT_MAP          299
#define IDS_KEYCONFIG_EDIT_TESTPLAY     300
#define IDS_KEYCONFIG_EDIT_PAGETESTPLAY 301
#define IDS_KEYCONFIG_EDIT_PAGETESTPLAY2 302
#define IDS_KEYCONFIG_EDIT_STOP         303
#define IDS_KEYCONFIG_EDIT_SAVEEMU      304
#define IDS_KEYCONFIG_EDIT_LOADEMU      305
#define IDS_KEYCONFIG_EDIT_EMUSETTING   306
#define IDS_KEYCONFIG_EDIT_NEXTWIN      307
#define IDS_KEYCONFIG_EDIT_PREVWIN      308
#define IDS_KEYCONFIG_KEYACCEL          309
#define IDS_KEYCONFIG_EMULATOR          310
#define IDS_KEYCONFIG_OVERLAPPED        311
#define IDS_KEYCONFIG_INITIALIZE        312
#define IDS_KEYCONFIG_NOTIFY            313
#define IDS_KEYCONFIG_PRESET_DESKTOP    314
#define IDS_KEYCONFIG_PRESET_NOTE       315
#define IDS_KEYCONFIG_WHEEL_NONE        316
#define IDS_KEYCONFIG_WHEEL_SHIFT       317
#define IDS_KEYCONFIG_WHEEL_CTRL        318
#define IDS_KEYCONFIG_WHEEL_SHIFTCTRL   319
#define IDS_KEYCONFIG_WHEEL_TYPE1       320
#define IDS_KEYCONFIG_WHEEL_TYPE16      321
#define IDS_KEYCONFIG_WHEEL_PAGE        322
#define IDS_KEYCONFIG_WHEEL_OBJ         323
#define IDS_KEYCONFIG_BUTTONX           324
#define IDS_OBJLIST_LENNAME             325
#define IDS_OBJLIST_UNKNOWN             326
#define IDS_OBJLIST_CRASH               327
#define IDS_OBJLIST_BACK                328
#define IDS_OBJLIST_VIEWBLOCK           329
#define IDS_OBJLIST_ROPE                330
#define IDS_OBJLIST_LENCASTLE           331
#define IDS_OBJLIST_STEP                332
#define IDS_OBJLIST_STEP98              333
#define IDS_OBJLIST_STEP98_2            334
#define IDS_OBJLIST_NONE                335
#define IDS_OBJLIST_ROOM                336
#define IDS_OBJLIST_PAGECOMMAND         337
#define IDS_OBJLIST_HARD                338
#define IDS_AREASORT_TITLE              339
#define IDS_SEA                         340
#define IDS_SKY                         341
#define IDS_UNDERGROUND                 342
#define IDS_CASTLE                      343
#define IDS_OBJLIST_COLUMN_BIN          344
#define IDS_OBJLIST_COLUMN_PAGE         345
#define IDS_OBJLIST_COLUMN_POS          346
#define IDS_OBJLIST_COLUMN_TYPE         347
#define IDS_OBJDATA_MAP_B_01            348
#define IDS_OBJDATA_MAP_B_02            349
#define IDS_OBJDATA_MAP_B_03            350
#define IDS_OBJDATA_MAP_B_04            351
#define IDS_OBJDATA_MAP_B_05            352
#define IDS_OBJDATA_MAP_B_06            353
#define IDS_OBJDATA_MAP_B_07            354
#define IDS_OBJDATA_MAP_B_08            355
#define IDS_OBJDATA_MAP_B_09            356
#define IDS_OBJDATA_MAP_B_10            357
#define IDS_OBJDATA_MAP_B_11            358
#define IDS_OBJDATA_MAP_B_12            359
#define IDS_OBJDATA_MAP_B_13            360
#define IDS_OBJDATA_MAP_B_14            361
#define IDS_OBJDATA_MAP_B_15            362
#define IDS_OBJDATA_MAP_B_16            363
#define IDS_OBJDATA_MAP_B_17            364
#define IDS_OBJDATA_MAP_B_18            365
#define IDS_OBJDATA_MAP_B_19            366
#define IDS_OBJDATA_MAP_B_20            367
#define IDS_OBJDATA_MAP_B_21            368
#define IDS_OBJDATA_MAP_B_22            369
#define IDS_OBJDATA_MAP_B_23            370
#define IDS_OBJDATA_MAP_B_24            371
#define IDS_OBJDATA_HELP_B12            372
#define IDS_OBJDATA_HELP_B13            373
#define IDS_OBJDATA_HELP_B14            374
#define IDS_OBJDATA_HELP_B23            375
#define IDS_OBJDATA_MAP_C_01            376
#define IDS_OBJDATA_MAP_C_02            377
#define IDS_OBJDATA_MAP_C_03            378
#define IDS_OBJDATA_MAP_C_04            379
#define IDS_OBJDATA_MAP_C_05            380
#define IDS_OBJDATA_MAP_C_06            381
#define IDS_OBJDATA_MAP_C_07            382
#define IDS_OBJDATA_MAP_C_08            383
#define IDS_OBJDATA_HELP_C01            384
#define IDS_OBJDATA_HELP_C02            385
#define IDS_OBJDATA_HELP_C06            386
#define IDS_OBJDATA_MAP_D_01            387
#define IDS_OBJDATA_MAP_D_02            388
#define IDS_OBJDATA_MAP_D_03            389
#define IDS_OBJDATA_MAP_D_04            390
#define IDS_OBJDATA_MAP_D_05            391
#define IDS_OBJDATA_MAP_D_06            392
#define IDS_OBJDATA_MAP_D_07            393
#define IDS_OBJDATA_MAP_D_08            394
#define IDS_OBJDATA_MAP_D_10            395
#define IDS_OBJDATA_MAP_D_11            396
#define IDS_OBJDATA_MAP_D_12            397
#define IDS_OBJDATA_MAP_D_13            398
#define IDS_OBJDATA_MAP_D_14            399
#define IDS_OBJDATA_MAP_D_15            400
#define IDS_OBJDATA_HELP_D01            401
#define IDS_OBJDATA_HELP_D03            402
#define IDS_OBJDATA_HELP_D04            403
#define IDS_OBJDATA_HELP_D05            404
#define IDS_OBJDATA_HELP_D06            405
#define IDS_OBJDATA_HELP_D12            406
#define IDS_OBJDATA_HELP_D13            407
#define IDS_OBJDATA_MAP_E_01            408
#define IDS_OBJDATA_MAP_E_02            409
#define IDS_OBJDATA_MAP_F_01            410
#define IDS_OBJDATA_MAP_F_02            411
#define IDS_OBJDATA_MAP_F_03            412
#define IDS_OBJDATA_MAP_F_04            413
#define IDS_OBJDATA_MAP_F_05            414
#define IDS_OBJDATA_MAP_F_06            415
#define IDS_OBJDATA_MAP_F_07            416
#define IDS_OBJDATA_MAP_F_08            417
#define IDS_OBJDATA_HELP_F01            418
#define IDS_OBJDATA_HELP_F02            419
#define IDS_OBJDATA_HELP_F03            420
#define IDS_OBJDATA_HELP_F05            421
#define IDS_OBJDATA_HELP_F07            422
#define IDS_OBJDATA_BB_01               423
#define IDS_OBJDATA_BB_02               424
#define IDS_OBJDATA_BB_03               425
#define IDS_OBJDATA_BB_04               426
#define IDS_OBJDATA_BB_05               427
#define IDS_OBJDATA_BB_06               428
#define IDS_OBJDATA_BB_07               429
#define IDS_OBJDATA_BB_08               430
#define IDS_OBJDATA_BB_09               431
#define IDS_OBJDATA_BB_10               432
#define IDS_OBJDATA_BB_11               433
#define IDS_OBJDATA_BB_12               434
#define IDS_OBJDATA_BB_13               435
#define IDS_OBJDATA_BB_14               436
#define IDS_OBJDATA_BB_15               437
#define IDS_OBJDATA_BB_16               438
#define IDS_OBJDATA_T_01                439
#define IDS_OBJDATA_T_02                440
#define IDS_OBJDATA_T_03                441
#define IDS_OBJDATA_T_04                442
#define IDS_OBJDATA_P_01                443
#define IDS_OBJDATA_P_02                444
#define IDS_OBJDATA_P_03                445
#define IDS_OBJDATA_P_04                446
#define IDS_OBJDATA_P_07                447
#define IDS_OBJDATA_BC_01               448
#define IDS_OBJDATA_BC_02               449
#define IDS_OBJDATA_BC_03               450
#define IDS_OBJDATA_BC_04               451
#define IDS_OBJDATA_BC_05               452
#define IDS_OBJDATA_BC_06               453
#define IDS_OBJDATA_BC_07               454
#define IDS_OBJDATA_BC_08               455
#define IDS_OBJDATA_MT_01               456
#define IDS_OBJDATA_MT_02               457
#define IDS_OBJDATA_MT_03               458
#define IDS_OBJDATA_MT_04               459
#define IDS_OBJDATA_V_01                460
#define IDS_OBJDATA_V_02                461
#define IDS_OBJDATA_V_03                462
#define IDS_OBJDATA_V_04                463
#define IDS_OBJDATA_BADGUYS_01          464
#define IDS_OBJDATA_BADGUYS_02          465
#define IDS_OBJDATA_BADGUYS_03          466
#define IDS_OBJDATA_BADGUYS_04          467
#define IDS_OBJDATA_BADGUYS_05          468
#define IDS_OBJDATA_BADGUYS_06          469
#define IDS_OBJDATA_BADGUYS_07          470
#define IDS_OBJDATA_BADGUYS_08          471
#define IDS_OBJDATA_BADGUYS_09          472
#define IDS_OBJDATA_BADGUYS_10          473
#define IDS_OBJDATA_BADGUYS_11          474
#define IDS_OBJDATA_BADGUYS_12          475
#define IDS_OBJDATA_BADGUYS_13          476
#define IDS_OBJDATA_BADGUYS_14          477
#define IDS_OBJDATA_BADGUYS_15          478
#define IDS_OBJDATA_BADGUYS_16          479
#define IDS_OBJDATA_BADGUYS_17          480
#define IDS_OBJDATA_BADGUYS_18          481
#define IDS_OBJDATA_BADGUYS_19          482
#define IDS_OBJDATA_BADGUYS_20          483
#define IDS_OBJDATA_BADGUYS_21          484
#define IDS_OBJDATA_BADGUYS_22          485
#define IDS_OBJDATA_BADGUYS_23          486
#define IDS_OBJDATA_BADGUYS_24          487
#define IDS_OBJDATA_BADGUYS_25          488
#define IDS_OBJDATA_BADGUYS_28          489
#define IDS_OBJDATA_BADGUYS_29          490
#define IDS_OBJDATA_BADGUYS_30          491
#define IDS_OBJDATA_BADGUYS_31          492
#define IDS_OBJDATA_BADGUYS_32          493
#define IDS_OBJDATA_BADGUYS_33          494
#define IDS_OBJDATA_BADGUYS_37          495
#define IDS_OBJDATA_BADGUYS_38          496
#define IDS_OBJDATA_BADGUYS_39          497
#define IDS_OBJDATA_BADGUYS_40          498
#define IDS_OBJDATA_BADGUYS_41          499
#define IDS_OBJDATA_BADGUYS_42          500
#define IDS_OBJDATA_BADGUYS_43          501
#define IDS_OBJDATA_BADGUYS_44          502
#define IDS_OBJDATA_BADGUYS_45          503
#define IDS_OBJDATA_BADGUYS_46          504
#define IDS_OBJDATA_BADGUYS_47          505
#define IDS_OBJDATA_BADGUYS_48          506
#define IDS_OBJDATA_BADGUYS_51          507
#define IDS_OBJDATA_BADGUYS_53          508
#define IDS_OBJDATA_BADGUYS_54          509
#define IDS_OBJDATA_BADGUYS_56          510
#define IDS_OBJDATA_BADGUYS_57          511
#define IDS_OBJDATA_BADGUYS_58          512
#define IDS_OBJDATA_BADGUYS_59          513
#define IDS_OBJDATA_BADGUYS_60          514
#define IDS_OBJDATA_BADGUYS_61          515
#define IDS_OBJDATA_BADGUYS_62          516
#define IDS_OBJDATA_BADGUYS_63          517
#define IDS_DELREG_TITLE                518
#define IDS_DELREG_CONFIRM              519
#define IDS_DELREG_COMPLETE             520
#define IDS_DELREG_ERROR_01             521

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        522
#define _APS_NEXT_COMMAND_VALUE         40052
#define _APS_NEXT_CONTROL_VALUE         2216
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
